name: publish docs

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: "pages-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.x'
          cache: 'poetry'

      - run: poetry install --only docs

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Build
        run: |
          mkdocs build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./site

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    needs:
      - build

    if: github.event == 'push' && github.ref_name == 'main'

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
